# Linear Regression 

In [1]:
import pandas as pd 
import numpy as np

In [4]:
df=pd.read_csv("boston.csv")
df

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0             0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1             1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2             2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3             3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4             4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501         501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1   
502         502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1   
503         503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1   
504         504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1   
505         505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1   

     TAX  PTRATIO       B  LSTAT  Price  
0    296     15.3  396.90   4.98   24.0  
1    242     17.8  396.90   9.14   21.6  
2    242     17.8  392.83   4.03   34.7  
3    222     18.7  394.63   2.94   33.4  
4    222     18.7  396.90   5.33   36.2  
..   ...      ...     ...    ...    ...  
501  273     21.0  391.99   9.67   22.4  
502  273     21.0  396.90   9.08   20.6  
503  273     21.0  396.90   5.64   23.9  
504  273     21.0  393.45   6.48   22.0  
505  273     21.0  396.90   7.88   11.9  

[506 rows x 15 columns]

In [5]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [6]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  Price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [7]:
# Independent and Dependent Data
x= df.drop("Price",axis=1)
y= df.Price

In [10]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
x_scaled=StandardScaler().fit_transform(x)

In [11]:
for i in df.columns:
    if i!="Price":
        df[i]=StandardScaler().fit_transform(df[[i]])
        df=df[df[i].between(-3,3)]

C:\Users\Dell\AppData\Local\Temp\ipykernel_25184\2743036019.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=StandardScaler().fit_transform(df[[i]])


In [12]:
df

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.419782  0.275323 -1.324242 -0.274874 -0.140856  0.479430 -0.106717   
1   -0.417339 -0.492566 -0.621709 -0.274874 -0.758367  0.250270  0.380883   
2   -0.417342 -0.492566 -0.621709 -0.274874 -0.758367  1.387140 -0.252642   
3   -0.416750 -0.492566 -1.343429 -0.274874 -0.856811  1.108875 -0.797189   
4   -0.412482 -0.492566 -1.343429 -0.274874 -0.856811  1.330594 -0.498222   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.413229 -0.492566  0.095583 -0.274874  0.172374  0.506215  0.032089   
502 -0.415249 -0.492566  0.095583 -0.274874  0.172374 -0.197633  0.302583   
503 -0.413447 -0.492566  0.095583 -0.274874  0.172374  1.076137  0.811538   
504 -0.407764 -0.492566  0.095583 -0.274874  0.172374  0.805312  0.751033   
505 -0.415000 -0.492566  0.095583 -0.274874  0.172374 -0.331557  0.448507   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  Price  
0    0.131724 -0.975748 -0.669004 -1.559902  0.440497 -1.120166   24.0  
1    0.558473 -0.860223 -0.991198 -0.371649  0.440497 -0.492671   21.6  
2    0.558473 -0.860223 -0.991198 -0.371649  0.395622 -1.263464   34.7  
3    1.091289 -0.744698 -1.110529  0.056123  0.415468 -1.427879   33.4  
4    1.091289 -0.744698 -1.110529  0.056123  0.440497 -1.067372   36.2  
..        ...       ...       ...       ...       ...       ...    ...  
501 -0.652295 -0.975748 -0.806235  1.149316  0.386361 -0.412726   22.4  
502 -0.745274 -0.975748 -0.806235  1.149316  0.440497 -0.501722   20.6  
503 -0.803659 -0.975748 -0.806235  1.149316  0.440497 -1.020611   23.9  
504 -0.695938 -0.975748 -0.806235  1.149316  0.402458 -0.893906   22.0  
505 -0.639450 -0.975748 -0.806235  1.149316  0.440497 -0.682730   11.9  

[412 rows x 14 columns]

In [16]:
simple_x= x[["CRIM"]] # Mx+c
# Multiple Regression [M1*x1 + M2*x2 +M3*x3+.....+C]

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.2)

In [19]:
(y_test.shape[0]/(y_test.shape[0]+y_train.shape[0]))*100

20.158102766798418

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
LR= LinearRegression()

In [22]:
LR

LinearRegression()

In [23]:
LR.fit(x_train,y_train)

LinearRegression()

In [24]:
predictions=LR.predict(x_test)

In [25]:
predictions

array([24.88963777, 23.72141085, 29.36499868, 12.12238621, 21.44382254,
       19.2834443 , 20.49647539, 21.36099298, 18.8967118 , 19.9280658 ,
        5.12703513, 16.3867396 , 17.07776485,  5.59375659, 39.99636726,
       32.49654668, 22.45798809, 36.85192327, 30.86401089, 23.15140009,
       24.77495789, 24.67187756, 20.59543752, 30.35369168, 22.41940736,
       10.23266565, 17.64816865, 18.27419652, 35.53362541, 20.96084724,
       18.30413012, 17.79262072, 19.96561663, 24.06127231, 29.10204874,
       19.27774123, 11.15536648, 24.57560579, 17.5862644 , 15.49454112,
       26.20577527, 20.86304693, 22.31460516, 15.60710156, 23.00363104,
       25.17247952, 20.11459464, 22.90256276, 10.0380507 , 24.28515123,
       20.94127711, 17.35258791, 24.52235405, 29.95143046, 13.42695877,
       21.72673066, 20.7897053 , 15.49668805, 13.98982601, 22.18377874,
       17.73047814, 21.58869165, 32.90522136, 31.11235671, 17.73252635,
       32.76358681, 18.7124637 , 19.78693475, 19.02958927, 22.89

In [17]:
pd.DataFrame({"Actual":y_test,"Prediction":predictions})

Actual  Prediction
329    22.6   24.889638
371    50.0   23.721411
219    23.0   29.364999
403     8.3   12.122386
78     21.2   21.443823
..      ...         ...
56     24.7   25.442171
455    14.1   15.571783
60     18.7   17.937195
213    28.1   25.305888
108    19.8   22.373233

[102 rows x 2 columns]

In [18]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [19]:
mean_squared_error(y_test,predictions)

33.44897999767657

In [20]:
mean_absolute_error(y_test,predictions)

3.842909220444503

In [21]:
import math

In [22]:
math.sqrt(mean_squared_error(y_test,predictions))

5.783509315085138

In [23]:
r2_score(y_test,predictions)

0.5892223849182503

In [24]:
LR.score(x_train,y_train)

0.7730135569264234

In [25]:
list(x.columns)

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

In [26]:
LR.predict(np.array([list(x.iloc[1,:])]))

C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25.17247952])

In [27]:
LR.predict(x)

array([30.49949836, 25.17247952, 30.54665354, 28.60694794, 27.96958264,
       25.33766463, 23.60318829, 20.25607099, 12.65147525, 19.69986884,
       19.78693475, 22.21068249, 21.72673066, 19.51737003, 19.2087374 ,
       19.2834443 , 20.55222254, 16.97107603, 16.44453732, 18.38505179,
       12.73233004, 17.64816865, 15.92613078, 13.95441929, 15.75342369,
       13.64649885, 15.56419667, 14.93078086, 19.46400572, 20.76322385,
       11.77477027, 17.98685071,  9.44489833, 14.42603011, 13.99145209,
       23.72500963, 22.3672764 , 23.15140009, 23.02767993, 31.36752127,
       34.12962592, 28.24902955, 25.51231449, 24.95294806, 23.24522425,
       22.41940736, 20.86304693, 18.45835276,  9.94954653, 17.7083025 ,
       21.81339391, 24.2966726 , 27.96372521, 24.50837677, 15.83515991,
       31.24428679, 25.44217132, 33.41315924, 21.79697632, 21.04977584,
       17.93719475, 18.47439387, 23.76669997, 22.55275499, 23.67278817,
       30.72859326, 26.07579718, 21.44652404, 17.88247152, 21.09

In [28]:
import joblib

In [29]:
import joblib

# Assuming your trained model is stored in a variable called 'model'
joblib.dump(LR, "house_price_model.pkl")

['house_price_model.pkl']

In [30]:
pwd

'D:\\class files\\weekedays\\1830\\Machine Learning'